version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "46ki75"
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "46ki75"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      aws-sdk:
        patterns:
          - "aws-config"
          - "aws-sdk*"
      notionrs-updates:
        patterns:
          - "notionrs"
          - "notionrs*"
      utoipa-updates:
        patterns:
          - "utoipa"
          - "utoipa*"
    assignees:
      - "46ki75"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "46ki75"
